export default [
	{
		title: '首页',
		path: '/dataManage/main',
		exact: true,
		component: 'DataManageMain',
	},
	{
		title: '业务管理',
		path: '/dataManage/businessManage',
		exact: true,
		component: 'BusinessManage',
		children: [
			{
				title: '新建业务',
				path: '/dataManage/businessManage/create',
				exact: true,
				component: 'BusinessCreateAndEdit',
				isHide: 'Y',
				type: 'create',
			},
			{
				title: '编辑业务',
				path: '/dataManage/businessManage/edit',
				exact: true,
				component: 'BusinessCreateAndEdit',
				isHide: 'Y',
				type: 'edit',
			},
			{
				title: '查看业务',
				path: '/dataManage/businessManage/businessPreview',
				exact: true,
				component: 'BusinessPreview',
				isHide: 'Y',
				type: 'preview',
				children: [
					{
						title: '新建信息系统',
						path: '/dataManage/businessManage/businessPreview/InfoSys/create',
						exact: true,
						component: 'InfoSysPreviewAndCreateAndEdit',
						isHide: 'Y',
						type: 'create',
					},
					{
						title: '查看信息系统',
						path: '/dataManage/businessManage/businessPreview/InfoSys/preview',
						exact: true,
						component: 'InfoSysPreviewAndCreateAndEdit',
						isHide: 'Y',
						type: 'preview',
					},

					{
						title: '编辑信息系统',
						path: '/dataManage/businessManage/businessPreview/InfoSys/edit',
						exact: true,
						component: 'InfoSysPreviewAndCreateAndEdit',
						isHide: 'Y',
						type: 'edit',
					},
					{
						title: '数据视图管理',
						path:
							'/dataManage/businessManage/businessPreview/InfoSys/viewsManage',
						exact: true,
						component: 'ViewsManage',
						isHide: 'Y',
						children: [
							{
								title: '查看数据视图',
								path:
									'/dataManage/businessManage/businessPreview/InfoSys/viewsManage/preview',
								exact: true,
								component: 'ViewsPreviewAndCreateAndEdit',
								isHide: 'Y',
								type: 'preview',
							},
							{
								title: '新建数据视图',
								path:
									'/dataManage/businessManage/businessPreview/InfoSys/viewsManage/create',
								exact: true,
								component: 'ViewsPreviewAndCreateAndEdit',
								isHide: 'Y',
								type: 'create',
							},
							{
								title: '编辑数据视图',
								path:
									'/dataManage/businessManage/businessPreview/InfoSys/viewsManage/edit',
								exact: true,
								component: 'ViewsPreviewAndCreateAndEdit',
								isHide: 'Y',
								type: 'edit',
							},
						],
					},
					{
						title: '查看表单',
						path: '/dataManage/businessManage/businessPreview/schema/preview',
						exact: true,
						component: 'SchemaPreviewAndCreateAndEdit',
						isHide: 'Y',
						type: 'preview',
					},
					{
						title: '新建表单',
						path: '/dataManage/businessManage/businessPreview/schema/create',
						exact: true,
						component: 'SchemaPreviewAndCreateAndEdit',
						isHide: 'Y',
						type: 'create',
					},
					{
						title: '编辑表单',
						path: '/dataManage/businessManage/businessPreview/schema/edit',
						exact: true,
						component: 'SchemaPreviewAndCreateAndEdit',
						isHide: 'Y',
						type: 'edit',
					},
				],
			},
		],
	},
	{
		title: '数据源管理',
		path: '/dataManage/dataSource',
		exact: true,
		component: 'DataManage',
		children: [
			{
				title: '新增数据源',
				path: '/dataManage/dataSource/create',
				exact: true,
				component: 'DataSourceCreateEditPreviewLayout',
				isHide: 'Y',
				type: 'create',
			},
			{
				title: '编辑数据源',
				path: '/dataManage/dataSource/edit',
				exact: true,
				component: 'DataSourceCreateEditPreviewLayout',
				isHide: 'Y',
				type: 'edit',
			},
			{
				title: '查看数据源',
				path: '/dataManage/dataSource/preview',
				exact: true,
				component: 'DataSourceCreateEditPreviewLayout',
				isHide: 'Y',
				type: 'preview',
			},
		],
	},
	{
		title: '数据资源管理',
		path: '/dataManage/dataReSource',
		exact: true,
		component: 'DataResource',
		children: [
			{
				title: '新增数据资源',
				path: '/dataManage/dataResource/create',
				exact: true,
				component: 'DataResourceCreateLayout',
				isHide: 'Y',
			},
			{
				title: '批量新增数据资源',
				path: '/dataManage/dataReSource/batchCreate',
				exact: true,
				component: 'DataResourceBatchCreateLayout',
				isHide: 'Y',
			},
			{
				title: '编辑数据资源',
				path: '/dataManage/dataReSource/edit',
				exact: true,
				component: 'DataResourceEditLayout',
				isHide: 'Y',
			},
			{
				title: '查看数据资源',
				path: '/dataManage/dataReSource/preview',
				exact: true,
				component: 'DataResourcePreviewLayout',
				isHide: 'Y',
			},
		],
	},
]
